version: '3.8'
services:
  web:
    build: .
    command: ./entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/vol/staticfiles
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mzuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mzpass}
      POSTGRES_DB: ${POSTGRES_DB:-mzdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/vol/staticfiles:ro
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/conf.d/:/etc/nginx/conf.d/:ro

volumes:
  postgres_data:
  static_volume:
