services:
  - type: web
    name: mzanzibari-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_production
      - key: SECRET_KEY
        value: "change-me-to-a-secure-random-key-in-render-dashboard"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "mzanzibari.onrender.com,*.render.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: mzanzibari-db
          property: connectionString

  - type: pserv
    name: mzanzibari-db
    plan: free
    ipAllowList: []
    postgreSQLVersion: "15"
